name: Deployment via Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to VPS and redeploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/projects/shorrt-link

            # Pull latest code
            git fetch --all
            git reset --hard origin/main

            cd backend

            # Rebuild and restart containers
            docker compose down
            docker compose up -d --build
